kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard-io1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10000"
reclaimPolicy: Retain
volumeBindingMode: Immediate