apiVersion: v1
kind: Service
metadata:
  name: prod-db-service-loadbalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-072e99ba638df3454,subnet-0e2334f9a8c7ce140"
spec:
  type: LoadBalancer
  selector:
    app: timescaledb
    cluster-name: timescaledb
    release: timescaledb
    app.kubernetes.io/component: timescaledb
    app.kubernetes.io/name: timescabledb
  ports:
    - port: 5432
      targetPort: 5432