apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-2-ebs-3.3tb-storage
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1a
    eks.amazonaws.com/nodegroup: iu-prod-data-platform-eks-cluster-nodegroup-one
    purpose: data-directory
    release: timescaledb2
    app: timescaledb2
spec:
  capacity:
    storage: 3.3Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: vol-0eef395128715f505
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-2-ebs-50gb-wal
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1a
    eks.amazonaws.com/nodegroup: iu-prod-data-platform-eks-cluster-nodegroup-one
    purpose: wal-directory
    release: timescaledb2
    app: timescaledb2
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: io2
  awsElasticBlockStore:
    volumeID: vol-088776ec8b7a90b55
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-2-ebs-5.3tb-storage-partition2
  labels:
    type: amazonEBS
    topology.kubernetes.io/zone: ap-south-1a
    eks.amazonaws.com/nodegroup: iu-prod-data-platform-eks-cluster-nodegroup-one
    purpose: tablespace
    tablespace: partition2
    release: timescaledb2
    app: timescaledb2
spec:
  capacity:
    storage: 5.3Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: vol-065392c1d5de44c8a
    fsType: ext4
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: prod-2-ebs-3.3tb-storage-partition3
#  labels:
#    type: amazonEBS
#    topology.kubernetes.io/zone: ap-south-1a
#    eks.amazonaws.com/nodegroup: iu-prod-data-platform-eks-cluster-nodegroup-one
#    purpose: tablespace
#    tablespace: partition3
#    release: timescaledb2
#    app: timescaledb2
#spec:
#  capacity:
#    storage: 3.3Ti
#  volumeMode: Filesystem
#  accessModes:
#  - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: gp3
#  awsElasticBlockStore:
#    volumeID: vol-0ce4347884a2ecc7f
#    fsType: ext4
