kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io2
  iopsPerGB: "3000"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer