kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "3000"
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer