apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-3-ebs-3.3tb-storage
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1b
    eks.amazonaws.com/nodegroup: iu-sit-ap-south-1-data-platform-eks-cluster-new-nodegroup-one
    purpose: data-directory
    release: timescaledb3
    app: timescaledb3
spec:
  capacity:
    storage: 3380Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: vol-0606c85c8fac12b1f
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-3-ebs-50gb-wal
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1b
    eks.amazonaws.com/nodegroup: iu-sit-ap-south-1-data-platform-eks-cluster-new-nodegroup-one
    purpose: wal-directory
    release: timescaledb3
    app: timescaledb3
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: io2
  awsElasticBlockStore:
    volumeID: vol-0f32fa7eeb847fe55
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-3-ebs-5tb-storage-partition2
  labels:
    type: amazonEBS
    topology.kubernetes.io/zone: ap-south-1b
    eks.amazonaws.com/nodegroup: iu-sit-ap-south-1-data-platform-eks-cluster-new-nodegroup-one
    purpose: tablespace
    tablespace: partition2
    release: timescaledb3
    app: timescaledb3
spec:
  capacity:
    storage: 5Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: vol-0deb50fd06d5318e3
    fsType: ext4