apiVersion: v1
kind: Service
metadata:
  name: prod-vol-prometheus-loadbalancer
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-monitoring-kube-prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
  loadBalancerSourceRanges:
  - "10.0.0.0/16"
  - "172.31.5.32/32"

