apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod1-ebs-12tb-storage
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1b
    eks.amazonaws.com/nodegroup: iu-prod-data-platform-eks-cluster-nodegroup-one
    purpose: data-directory

spec:
  capacity:
    storage: 12Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: io2
  awsElasticBlockStore:
    volumeID: vol-0e41afe8a2c0d9f20
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod1-ebs-150gb-wal
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1b
    eks.amazonaws.com/nodegroup: iu-prod-data-platform-eks-cluster-nodegroup-one
    purpose: wal-directory
spec:
  capacity:
    storage: 150Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: io2
  awsElasticBlockStore:
    volumeID: vol-0679d141daa4001c3
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod1-ebs-10tb-partition1
  labels:
    type: amazonEBS
    topology.kubernetes.io/zone: ap-south-1b
    eks.amazonaws.com/nodegroup: iu-prod-data-platform-eks-cluster-nodegroup-one
    purpose: tablespace
    tablespace: partition1
spec:
  capacity:
    storage: 10Ti
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: io1
  awsElasticBlockStore:
    volumeID: vol-0d4d6d98907950900
    fsType: ext4

