apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod5-ebs-50gb-storage
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1a
    eks.amazonaws.com/nodegroup: iu-prod-data-platform-eks-cluster-nodegroup-one
    purpose: data-directory

spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: vol-05ec58e062bcc3eaf
    fsType: ext4