apiVersion: v1
kind: PersistentVolume
metadata:
  name: sti-ebs-150gb-wal
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1a
    eks.amazonaws.com/nodegroup: iu-sit-ap-south-1-data-platform-eks-cluster-new-nodegroup-one
spec:
  capacity:
    storage: 150Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  # claimRef:
  #   namespace: timescaledb
  #   name: wal-volume-timescaledb-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-01
  awsElasticBlockStore:
    volumeID: vol-00fef2108d593fc83
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sti-ebs-200gb-storage
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1a
    eks.amazonaws.com/nodegroup: iu-sit-ap-south-1-data-platform-eks-cluster-new-nodegroup-one
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  # claimRef:
  #   namespace: timescaledb
  #   name: storage-volume-timescaledb-0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2-01
  awsElasticBlockStore:
    volumeID: vol-0aff2c771240c5315
    fsType: ext4
