apiVersion: v1
kind: PersistentVolume
metadata:
  name: uat-ebs-50gb-wal
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1a
    eks.amazonaws.com/nodegroup: iu-uat-data-platform-eks-cluster-nodegroup-one
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # claimRef:
  #   namespace: timescaledb
  #   name: wal-volume-timescaledb-uat-0
  storageClassName: io1
  awsElasticBlockStore:
    volumeID: vol-0ae80cb40c9829679
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uat-ebs-210gb-storage
  labels:
    type: amazonEBS
    failure-domain.beta.kubernetes.io/region: ap-south-1
    failure-domain.beta.kubernetes.io/zone: ap-south-1a
    eks.amazonaws.com/nodegroup: iu-uat-data-platform-eks-cluster-nodegroup-one
spec:
  capacity:
    storage: 210Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # claimRef:
  #   namespace: timescaledb
  #   name: storage-volume-timescaledb-uat-0
  storageClassName: gp3
  awsElasticBlockStore:
    volumeID: vol-0f9191f116459d456
    fsType: ext4
