apiVersion: v1
kind: Service
metadata:
  name: uat-db2-service-loadbalancer
  namespace: timescaledb2
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-attributes: deletion_protection.enabled=true
spec:
  type: LoadBalancer
  selector:
    app: timescaledb2
    release: timescaledb2
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
  - name: pg-exporter
    port: 9187
    targetPort: 9187
